#!/usr/bin/env -S node --
'use strict'

const { run } = require('./dist/main.js')

run(process.argv.slice(2), process)
  .then(exitCode => {
    process.exitCode = exitCode
  })
  .catch(error => {
    process.stderr.write(`ERROR: internal_error ${error.name}\n`)
    process.exitCode = 4
  })
